### ISSUE TITLE
java代码操作hbase报错

### ISSUE THREAD

**Issue by wanghaopan** [wanghaopan/myself#8]
报错1：
javax.security.auth.login.LoginException: Zookeeper client cannot authenticate using the 'Client' section of the supplied JAAS configuration: 'D:\wanghaopan\code\hdfs\src\main\resources\jaas.conf' because of a RuntimeException: java.lang.SecurityException: java.io.IOException: 配置错误: 
	行 4: 应为 [option key], 找到 [null]
	at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:181)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1171)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1220)
2022-03-15 14:27:24,657 INFO  [ReadOnlyZKClient-bigdata-node-master3mips:24002,bigdata-node-master1cqnp:24002,bigdata-node-master2crfx:24002@0x52e6fdee-SendThread(bigdata-node-master1cqnp:24002)] zookeeper.ClientCnxn: Opening socket connection to server bigdata-node-master1cqnp/10.10.1.151:24002.
2022-03-15 14:27:24,658 INFO  [ReadOnlyZKClient-bigdata-node-master3mips:24002,bigdata-node-master1cqnp:24002,bigdata-node-master2crfx:24002@0x52e6fdee-SendThread(bigdata-node-master1cqnp:24002)] zookeeper.ClientCnxn: Socket connection established, initiating connection, client: /10.10.1.69:63240, server: bigdata-node-master1cqnp/10.10.1.151:24002
2022-03-15 14:27:24,659 INFO  [ReadOnlyZKClient-bigdata-node-master3mips:24002,bigdata-node-master1cqnp:24002,bigdata-node-master2crfx:24002@0x52e6fdee-SendThread(bigdata-node-master1cqnp:24002)] zookeeper.ClientCnxn: Connection establishment complete on server bigdata-node-master1cqnp/10.10.1.151:24002, connection id = 0x14003d2419623497, negotiated timeout = 90000
2022-03-15 14:27:25,342 WARN  [ReadOnlyZKClient-bigdata-node-master3mips:24002,bigdata-node-master1cqnp:24002,bigdata-node-master2crfx:24002@0x52e6fdee-SendThread(bigdata-node-master1cqnp:24002)] zookeeper.ClientCnxn: Connection 0x14003d2419623497 for sever bigdata-node-master1cqnp/10.10.1.151:24002, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
EndOfStreamException: Unable to read additional data from server connectionid 0x14003d2419623497, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:352)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1302)

报错2：WARN  [ReadOnlyZKClient-bigdata-node-master3mips:24002,bigdata-node-master1cqnp:24002,bigdata-node-master2crfx:24002@0x52e6fdee-SendThread(bigdata-node-master2crfx:24002)] zookeeper.ClientCnxn: SASL configuration failed. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it.
javax.security.auth.login.LoginException: No password provided
	at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:923)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:764)
	at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.zookeeper.Login.login(Login.java:318)
	at org.apache.zookeeper.Login.<init>(Login.java:100)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.createSaslClient(ZooKeeperSaslClient.java:245)
	at org.apache.zookeeper.client.ZooKeeperSaslClient.<init>(ZooKeeperSaslClient.java:139)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1171)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1220)
Debug is  true storeKey false useTicketCache true useKeyTab false doNotPrompt false ticketCache is null isInitiator true KeyTab is null refreshKrb5Config is false principal is null tryFirstPass is false useFirstPass is false storePass is false clearPass is false
Acquire TGT from Cache
Principal is null
null credentials from Ticket Cache
		[Krb5LoginModule] authentication failed 
No password provided

**Comment by wanghaopan** [comment]
这是因为zk和hbase都是开安全的，方法1、代码中使用  javax.security.auth.login.Configuration.setConfiguration(Configuration configuration)方法,需要继承Configuration类实现方法。    /**
     * copy from hbase zkutil 0.94&0.98 A JAAS configuration that defines the login modules that we want to use for
     * login.
     */
    private static class JaasConfiguration extends javax.security.auth.login.Configuration
    {
        private static final String SERVER_KEYTAB_KERBEROS_CONFIG_NAME = "zookeeper-server-keytab-kerberos";

        private static final String CLIENT_KEYTAB_KERBEROS_CONFIG_NAME = "zookeeper-client-keytab-kerberos";

        private static final Map BASIC_JAAS_OPTIONS = new HashMap();
        static
        {
            String jaasEnvVar = System.getenv("HBASE_JAAS_DEBUG");
            if (jaasEnvVar != null && "true".equalsIgnoreCase(jaasEnvVar))
            {
                BASIC_JAAS_OPTIONS.put("debug", "true");
            }
        }

        private static final Map KEYTAB_KERBEROS_OPTIONS = new HashMap();
        static
        {
            KEYTAB_KERBEROS_OPTIONS.put("doNotPrompt", "true");
            KEYTAB_KERBEROS_OPTIONS.put("storeKey", "true");
            KEYTAB_KERBEROS_OPTIONS.put("refreshKrb5Config", "true");
            KEYTAB_KERBEROS_OPTIONS.putAll(BASIC_JAAS_OPTIONS);
        }

        private static final AppConfigurationEntry KEYTAB_KERBEROS_LOGIN = new AppConfigurationEntry(
                KerberosUtil.getKrb5LoginModuleName(), LoginModuleControlFlag.REQUIRED, KEYTAB_KERBEROS_OPTIONS);

        private static final AppConfigurationEntry[] KEYTAB_KERBEROS_CONF =
                new AppConfigurationEntry[] {KEYTAB_KERBEROS_LOGIN};

        private javax.security.auth.login.Configuration baseConfig;

        private final String loginContextName;

        private final boolean useTicketCache;

        private final String keytabFile;

        private final String principal;

        public JaasConfiguration(String loginContextName, String principal)
        {
            this(loginContextName, principal, null, true);
        }

        public JaasConfiguration(String loginContextName, String principal, String keytabFile)
        {
            this(loginContextName, principal, keytabFile, keytabFile == null || keytabFile.length() == 0);
        }

        private JaasConfiguration(String loginContextName, String principal, String keytabFile, boolean useTicketCache)
        {
            try
            {
                this.baseConfig = javax.security.auth.login.Configuration.getConfiguration();
            }
            catch (SecurityException e)
            {
                this.baseConfig = null;
            }
            this.loginContextName = loginContextName;
            this.useTicketCache = useTicketCache;
            this.keytabFile = keytabFile;
            this.principal = principal;
            LOG.info("JaasConfiguration loginContextName=" + loginContextName + " principal=" + principal
                    + " useTicketCache=" + useTicketCache + " keytabFile=" + keytabFile);
        }

        public AppConfigurationEntry[] getAppConfigurationEntry(String appName)
        {
            if (loginContextName.equals(appName))
            {
                if (!useTicketCache)
                {
                    KEYTAB_KERBEROS_OPTIONS.put("keyTab", keytabFile);
                    KEYTAB_KERBEROS_OPTIONS.put("useKeyTab", "true");
                }
                KEYTAB_KERBEROS_OPTIONS.put("principal", principal);
                KEYTAB_KERBEROS_OPTIONS.put("useTicketCache", useTicketCache ? "true" : "false");
                return KEYTAB_KERBEROS_CONF;
            }
            if (baseConfig != null)
                return baseConfig.getAppConfigurationEntry(appName);
            return (null);
        }
    }

或者方法2、Configuration conf = HBaseConfiguration.create();
System.setProperty("java.security.auth.login.configl", "jaas.conf的路径");
UserGroupInformation.setConfiguration(conf); 
jaas.conf中需要有
Client {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=true
keyTab="xxxx\\user.keytab"
principal="xxxx"
useTicketCache=true
debug=false;
};
